### ISSUE TITLE
add support for category and product editing

### ISSUE THREAD

**Issue by EliasZ** [avstudnitz/AvS_ScopeHint2#4]
If you are not already working on this, might be able to fix it.

**Comment by avstudnitz** [comment]
I am not. That would be great!

**Comment by peterjaap** [comment]
Any news on this?

**Comment by peterjaap** [comment]
As it turns out, @EliasZ and @guido7171 already worked on this internally, I've created a WIP PR if someone feel likes picking it up from here; https://github.com/avstudnitz/AvS_ScopeHint2/pull/5

As far as I gathered from Guido, the current approach does a lot of data fetching in a loop and causes the backend to slow down considerably. So a slighty different approach would be advisable.

**Comment by peterjaap** [comment]
Maybe @guido7171 can shed some light on this?

**Comment by rikwillems** [comment]
Added PR #9

**Comment by peterjaap** [comment]
Merged by now! :tada:

**Comment by peterjaap** [comment]
@avstudnitz could you close this issue?

**Comment by avstudnitz** [comment]
Sure :-)
